name: Build and deploy to MonsterASP v2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Publish
        run: dotnet publish NotaionWebApp/Notaion/Notaion.csproj -c Release -o ./publish

      - name: Deploy via Web Deploy
        run: |
          msdeploy -verb:sync `
            -source:contentPath="${{ github.workspace }}\publish" `
            -dest:contentPath="site8642",`
              computerName="https://site8642.siteasp.net/msdeploy.axd",`
              userName="site8642",`
              password="fS=3#5XaWe4_",`
              authtype="Basic",`
              includeAcls="False" `
            -allowUntrusted `
            -enableRule:AppOffline
